name: CI

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  checks:
    name: Vérifications de base
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Vérifier le respect de .editorconfig
        uses: editorconfig-checker/action-editorconfig-checker@v2

      - run: editorconfig-checker
